name: style
on: [push, workflow_dispatch]

jobs:
  style:
    name: style
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - working-directory: C
        run: ./autoformat.bash check
