name: tests
on: [push, workflow_dispatch]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          make -j
          target/tests
